export const SKILLS_LIST = [
  { title: "Angular", value: "angular" },
  { title: "Ant Design", value: "ant_design" },
  { title: "Anthropic API", value: "anthropic_api" },
  { title: "Apache Kafka", value: "kafka" },
  { title: "Apollo Client", value: "apollo_client" },
  { title: "Astro", value: "astro" },
  { title: "Auth.js", value: "authjs" },
  { title: "Auth0", value: "auth0" },
  { title: "AWS", value: "aws" },
  { title: "Axios", value: "axios" },
  { title: "Babel", value: "babel" },
  { title: "BetterAuth", value: "betterauth" },
  { title: "Bootstrap", value: "bootstrap" },
  { title: "Chakra UI", value: "chakra_ui" },
  { title: "CircleCI", value: "circleci" },
  { title: "Clerk", value: "clerk" },
  { title: "Cloudflare Workers", value: "cloudflare_workers" },
  { title: "Contentful", value: "contentful" },
  { title: "Convex", value: "convex" },
  { title: "CSS", value: "css" },
  { title: "DeepSeek", value: "deepseek_api" },
  { title: "CSS Modules", value: "css_modules" },
  { title: "Cypress", value: "cypress" },
  { title: "DaisyUI", value: "daisyui" },
  { title: "Dart", value: "dart" },
  { title: "Directus", value: "directus" },
  { title: "Django", value: "django" },
  { title: "Docker", value: "docker" },
  { title: "Drizzle ORM", value: "drizzle" },
  { title: "DynamoDB", value: "dynamodb" },
  { title: "Elasticsearch", value: "elasticsearch" },
  { title: "Electron", value: "electron" },
  { title: "Emotion", value: "emotion" },
  { title: "esbuild", value: "esbuild" },
  { title: "ESLint", value: "eslint" },
  { title: "Expo", value: "expo" },
  { title: "Express.js", value: "expressjs" },
  { title: "Gemini", value: "gemini_api" },
  { title: "FastAPI", value: "fastapi" },
  { title: "Fastify", value: "fastify" },
  { title: "Figma", value: "figma" },
  { title: "Firebase", value: "firebase" },
  { title: "Flask", value: "flask" },
  { title: "Flutter", value: "flutter" },
  { title: "Fly.io", value: "flyio" },
  { title: "Framer Motion", value: "framer_motion" },
  { title: "Gatsby", value: "gatsby" },
  { title: "Git", value: "git" },
  { title: "GitHub", value: "github" },
  { title: "GitHub Actions", value: "github_actions" },
  { title: "GitLab", value: "gitlab" },
  { title: "GitLab CI/CD", value: "gitlab_cicd" },
  { title: "Go", value: "go" },
  { title: "Google Cloud (GCP)", value: "gcp" },
  { title: "Groq", value: "groq_api" },
  { title: "GraphQL", value: "graphql" },
  { title: "GSAP", value: "gsap" },
  { title: "Hono", value: "hono" },
  { title: "HTML", value: "html" },
  { title: "Hugging Face", value: "hugging_face" },
  { title: "Inngest", value: "inngest" },
  { title: "Java", value: "java" },
  { title: "JavaScript", value: "javascript" },
  { title: "Jest", value: "jest" },
  { title: "Jotai", value: "jotai" },
  { title: "JWT", value: "jwt" },
  { title: "Knex.js", value: "knex" },
  { title: "Kotlin", value: "kotlin" },
  { title: "Kubernetes", value: "kubernetes" },
  { title: "LangChain", value: "langchain" },
  { title: "Laravel", value: "laravel" },
  { title: "Linux", value: "linux" },
  { title: "Lottie", value: "lottie" },
  { title: "Material UI", value: "material_ui" },
  { title: "Microsoft Azure", value: "azure" },
  { title: "MobX", value: "mobx" },
  { title: "MongoDB", value: "mongodb" },
  { title: "Mongoose", value: "mongoose" },
  { title: "MySQL", value: "mysql" },
  { title: "NativeWind", value: "nativewind" },
  { title: "NestJS", value: "nestjs" },
  { title: "Neon", value: "neon" },
  { title: "Netlify", value: "netlify" },
  { title: "Next.js", value: "nextjs" },
  { title: "NextAuth.js", value: "nextauth" },
  { title: "Nginx", value: "nginx" },
  { title: "Node.js", value: "nodejs" },
  { title: "Nuxt.js", value: "nuxtjs" },
  { title: "Nx", value: "nx" },
  { title: "Ollama", value: "ollama" },
  { title: "OpenAI API", value: "openai_api" },
  { title: "Parcel", value: "parcel" },
  { title: "Passport.js", value: "passportjs" },
  { title: "Payload CMS", value: "payload_cms" },
  { title: "PHP", value: "php" },
  { title: "Pinia", value: "pinia" },
  { title: "Playwright", value: "playwright" },
  { title: "Polar", value: "polar" },
  { title: "PostgreSQL", value: "postgresql" },
  { title: "Prettier", value: "prettier" },
  { title: "Prisma", value: "prisma" },
  { title: "PWA", value: "pwa" },
  { title: "Python", value: "python" },
  { title: "Qwik", value: "qwik" },
  { title: "RabbitMQ", value: "rabbitmq" },
  { title: "Radix UI", value: "radix_ui" },
  { title: "Railway", value: "railway" },
  { title: "React", value: "react" },
  { title: "React Native", value: "react_native" },
  { title: "React Query", value: "react_query" },
  { title: "React Spring", value: "react_spring" },
  { title: "Recoil", value: "recoil" },
  { title: "Redis", value: "redis" },
  { title: "Redux Toolkit", value: "redux_toolkit" },
  { title: "RevenueCat", value: "revenuecat" },
  { title: "Remix", value: "remix" },
  { title: "Render", value: "render" },
  { title: "REST API", value: "rest_api" },
  { title: "Rollup", value: "rollup" },
  { title: "Ruby", value: "ruby" },
  { title: "Ruby on Rails", value: "rails" },
  { title: "Rust", value: "rust" },
  { title: "Sanity", value: "sanity" },
  { title: "Sass / SCSS", value: "sass" },
  { title: "Sequelize", value: "sequelize" },
  { title: "Shadcn/UI", value: "shadcn_ui" },
  { title: "Socket.io", value: "socket_io" },
  { title: "Solid.js", value: "solidjs" },
  { title: "Spring Boot", value: "spring_boot" },
  { title: "SQLite", value: "sqlite" },
  { title: "Storybook", value: "storybook" },
  { title: "Strapi", value: "strapi" },
  { title: "Stripe", value: "stripe" },
  { title: "Styled Components", value: "styled_components" },
  { title: "Supabase", value: "supabase" },
  { title: "Svelte", value: "svelte" },
  { title: "SvelteKit", value: "sveltekit" },
  { title: "Swagger / OpenAPI", value: "swagger" },
  { title: "SWC", value: "swc" },
  { title: "Swift", value: "swift" },
  { title: "SwiftUI", value: "swiftui" },
  { title: "SWR", value: "swr" },
  { title: "Tailwind CSS", value: "tailwindcss" },
  { title: "Tauri", value: "tauri" },
  { title: "Terraform", value: "terraform" },
  { title: "Testing Library", value: "testing_library" },
  { title: "Three.js", value: "threejs" },
  { title: "tRPC", value: "trpc" },
  { title: "Turbopack", value: "turbopack" },
  { title: "Turborepo", value: "turborepo" },
  { title: "TypeORM", value: "typeorm" },
  { title: "TypeScript", value: "typescript" },
  { title: "Vercel", value: "vercel" },
  { title: "Vite", value: "vite" },
  { title: "Vitest", value: "vitest" },
  { title: "Vue.js", value: "vuejs" },
  { title: "WebAssembly", value: "wasm" },
  { title: "Webpack", value: "webpack" },
  { title: "WebSockets", value: "websockets" },
  { title: "WordPress", value: "wordpress" },
  { title: "XState", value: "xstate" },
  { title: "Zod", value: "zod" },
  { title: "Zustand", value: "zustand" },
] as const;

export type SkillValue = (typeof SKILLS_LIST)[number]["value"];
